version: 2.1
jobs:
  build:
    parameters:
      jdk-version:
        type: string
    working_directory: ~/circleci-arquillian-cube
    docker:
      - image: cimg/openjdk:<< parameters.jdk-version >>
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: true
      - restore_cache:
          key: circleci-arquillian-cube-{{ checksum "pom.xml" }}
      - run:
          name: "Change owner of /var/run/docker.sock to circleci for local CLI builds"
          command: |
              if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
              echo 'Changing owner of /var/run/docker.sock to circleci' 
                  sudo chown circleci /var/run/docker.sock
              fi
      - run: ./mvnw verify -q -U -DskipTests # pre-fetch dependencies (dependency:resolve fails)
      - run: ./mvnw package
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-arquillian-cube-{{ checksum "pom.xml" }}

workflows:
  version: 2.1
  circleci_build:
    jobs:
      - build:
          matrix:
            parameters:
              jdk-version: ["8.0"] # TODO: Add JDK 11.0 when builds for JDK8 work
